name: Track TSC Attendance

on:
  workflow_dispatch:  # Manual trigger

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run attendance tracker
        run: python .github/workflows/track_attendance.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: tsc-attendance-report
          path: tsc_attendance_tracker.csv
  
      - name: Generate Markdown summary
        run: |
          python .github/workflows/track_attendance.py --markdown > attendance_summary.md

      - name: Post summary as comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number || github.run_id }}
          body-file: attendance_summary.md
