name: TSC Attendance Report

on:
  workflow_dispatch:

env:
  MEMBERS: |
    Hendrik Ebbers
    Richard Bair
    Leemon Baird
    Stoyan Panayotov
    George Spasov
    Alexander Popowycz
    Michael Kantor
    Milan Wiercx van Rhijn

jobs:
  tsc-attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate TSC Attendance Report
        run: |
          set -e

          echo "🔍 Parsing TSC attendance report..."

          # Join dates
          declare -A join_dates
          join_dates["Michael Kantor"]="2025-06-03"
          join_dates["Milan Wiercx van Rhijn"]="2025-06-03"

          # Read members
          IFS=$'\n' read -d '' -r -a all_members <<< "$MEMBERS"

          # Attendance tracking
          declare -A absence_streak
          declare -A presence_streak
          declare -A suspended

          echo ""
          printf "| Date | Member | Present | TSC Count | Quorum Required | Suspended | Voting Status | Eligible Members | Quorum | Quorum Met | Meeting Failed Quorum |\n"
          printf "|------|--------|---------|-----------|------------------|-----------|----------------|------------------|--------|-------------|------------------------|\n"

          for file in $(ls tsc/minutes/*.md | sort); do
            date=$(basename "$file" .md | cut -d'-' -f1-3)

            # Determine TSC members for the date
            current_members=()
            for member in "${all_members[@]}"; do
              join_date="${join_dates["$member"]}"
              if [[ -z "$join_date" || "$date" >= "$join_date" ]]; then
                current_members+=("$member")
              fi
            done

            tsc_count=${#current_members[@]}
            quorum_required=$(( (2 * tsc_count + 2) / 3 ))

            # Get attendees from section
            attendees=$(awk '/## TSC Attendees/{flag=1; next} /^## /{flag=0} flag && NF' "$file" | tr -d '*' | sed 's/^ *- *//' | tr -d '\r' | sort)

            eligible_count=0
            present_eligible_count=0

            for member in "${current_members[@]}"; do
              present="absent"
              voting_status="Eligible"
              is_suspended="${suspended["$member"]:-false}"

              if echo "$attendees" | grep -Fqx "$member"; then
                present="present"
                presence_streak["$member"]=$(( ${presence_streak["$member"]:-0} + 1 ))
                absence_streak["$member"]=0

                if [[ "${suspended["$member"]}" == "true" && "${presence_streak["$member"]}" -ge 2 ]]; then
                  suspended["$member"]="false"
                  is_suspended="false"
                fi
              else
                absence_streak["$member"]=$(( ${absence_streak["$member"]:-0} + 1 ))
                presence_streak["$member"]=0

                if [[ "${absence_streak["$member"]}" -ge 3 ]]; then
                  suspended["$member"]="true"
                  is_suspended="true"
                fi
              fi

              if [[ "$is_suspended" ==_]()]()
