name: TSC Attendance Report

on:
  workflow_dispatch:

env:
  MEMBERS: |
    Hendrik Ebbers
    Richard Bair
    Leemon Baird
    Stoyan Panayotov
    George Spasov
    Alexander Popowycz
    Michael Kantor
    Milan Wiercx van Rhijn

jobs:
  tsc-attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate TSC Attendance Table
        run: |
          set -e

          echo "Parsing TSC attendance..."

          # Step 1: Define member join dates
          declare -A join_date
          join_date["Michael Kantor"]="2025-06-03"
          join_date["Milan Wiercx van Rhijn"]="2025-06-03"

          # Step 2: Load member list into array
          IFS=$'\n' read -d '' -r -a all_members <<< "$MEMBERS"

          # Step 3: Tracking maps
          declare -A absences
          declare -A presents
          declare -A suspension_status
          declare -A presence_streak
          declare -A absence_streak

          printf "| Date | Member | Present | TSC Count | Quorum Required | Suspended | Voting Status | Eligible Members | Quorum | Quorum Met | Meeting Failed Quorum |\n"
          printf "|------|--------|---------|-----------|------------------|-----------|----------------|------------------|--------|-------------|------------------------|\n"

          for file in $(ls tsc/minutes/*.md | sort); do
            filename=$(basename "$file")
            date=${filename:0:10}

            attendees=$(awk '/## TSC Attendees/{flag=1; next} /^## /{flag=0} flag && NF' "$file" | tr -d '*' | sed 's/^- *//' | tr -d '\r')
            attendees=$(echo "$attendees" | sort)

            # Step 4: Determine current TSC members
            current_members=()
            for member in "${all_members[@]}"; do
              jd="${join_date[$member]}"
              if [[ -z "$jd" || "$date" >= "$jd" ]]; then
                current_members+=("$member")
              fi
            done

            tsc_count=${#current_members[@]}
            quorum_required=$(( (2 * tsc_count + 2) / 3 ))

            eligible_members=0
            eligible_present=0

            # Step 5: Evaluate each member
            for member in "${current_members[@]}"; do
              present="absent"
              suspended="${suspension_status[$member]:-false}"

              if echo "$attendees" | grep -Fqx "$member"; then
                present="present"
                presents["$member"]=$(( ${presents["$member"]:-0} + 1 ))
                absence_streak["$member"]=0
                presence_streak["$member"]=$(( ${presence_streak["$member"]:-0} + 1 ))

                if [[ "$suspended" == "true" && ${presence_streak["$member"]} -ge 2 ]]; then
                  suspended="false"
                  suspension_status["$member"]="false"
                fi
              else
                present="absent"
                absences["$member"]=$(( ${absences["$member"]:-0} + 1 ))
                presence_streak["$member"]=0
                absence_streak["$member"]=$(( ${absence_streak["$member"]:-0} + 1 ))

                if [[ ${absence_streak["$member"]} -ge 3 ]]; then
                  suspended="true"
                  suspension_status["$member"]="true"
                fi
              fi

              voting_status="Eligible"
              if [[ "$suspended" == "true" ]]; then
                voting_status="Suspended"
              else
                ((eligible_members++))
              fi

              if [[ "$present" == "present" && "$voting_status" == "Eligible" ]]; then
                ((eligible_present++))
              fi

              printf "| %s | %s | %s | %d | %d | %s | %s | - | - | - | - |\n" \
                "$date" "$member" "$present" "$tsc_count" "$quorum_required" "$suspended" "$voting_status"
            done

            quorum=$(( (2 * eligible_members + 2) / 3 ))
            quorum_met="false"
            failed_quorum="true"
            if [[ $eligible_present -ge $quorum ]]; then
              quorum_met="true"
              failed_quorum="false"
            fi

            printf "| %s | - | - | %d | %d | - | - | %d | %d | %s | %s |\n\n" \
              "$date" "$tsc_count" "$quorum_required" "$eligible_members" "$quorum" "$quorum_met" "$failed_quorum"
          done
